### ISSUE TITLE
optimization failed for a cpmd

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#292] opened 2023-10-24 14:44 UTC
**Description**

I tried to run bespokefit with xTB and psi4 but the optimisation failed for this cpmd.

**Reproduction**

```
openff-bespoke executor run --smiles             "c1cc(cc(c1)NC2CC[NH2+]CC2)C3=C(C(=C(S3)C(=O)[O-])OCC(=O)[O-])Br"    \
                            --workflow           "default"              \
                            --output             "mol.json"   \
                            --output-force-field "mol.offxml" \
                            --n-qc-compute-workers 4                    \
                            --qc-compute-n-cores   1                    \
                            --default-qc-spec xtb gfn2xtb none
```

**Output**

```
──────────────────────────────── OpenFF Bespoke ────────────────────────────────

[✓] bespoke executor launched

1. preparing the bespoke workflow                                               
                                                                                
[✓] 1 molecules found

[✓] fitting schemas generated
                                                                                
2. submitting the workflow                                                      
                                                                                

[✓] the following workflows were submitted
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━┓
┃ ID ┃ SMILES                                                    ┃ NAME ┃ FILE ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━┩
│ 1  │ c1cc(cc(c1)NC2CC[NH2+]CC2)C3=C(C(=C(S3)C(=O)[O-])OCC(=O)[ │      │      │
│    │ O-])Br                                                    │      │      │
└────┴───────────────────────────────────────────────────────────┴──────┴──────┘
                                                                                
3. running the fitting pipeline                                                 
                                                                                
[✓] fragmentation successful
[✓] qc-generation successful
[x] optimization failed
                                                                                
 "Failed to inject the bespoke QC data into the optimization schema: 1          
 validation error for TorsionProfileTargetSchema\nreference_data\n  Target      
 record -30: Reference data does not match target.\nExpected mapped SMILES:     
 [H:1]1((((1[H:8])[N:9]([H:10])[C:11]2([C:16]([C:15]([N+:14]([C:13]([C:12]2([H:2
 5])[H:26])([H:23])[H:24])([H:21])[H:22])([H:19])[H:20])([H:17])[H:18])[H:27])[H
 :28])[C:29]3=[C:30]([C:31](=[C:32]([S:33]3)[C:34](=[O:35])[O-:36])[H:37])[H:38]
 )[H:39]\nThe following connections were expected but not found: {(14, 21)}\nThe
 following connections were found but not expected: {(21, 36)}\nThe reference   
 geometry is: [[  2.98444212   0.63423433   4.40454938]\n [  1.09888233         
 1.29133868   4.82796706]\n [  0.19968809   1.14055257   7.27579248]\n [        
 -2.23911207   1.99106817   7.82043153]\n [ -3.72788702   2.96696328            
 5.88185505]\n [ -2.84446968   3.09885882   3.40503241]\n [ -0.38644883         
 2.25154958   2.91219244]\n [  0.34244167   2.35665619   1.00645387]\n [        
 -4.22452117   4.18917931   1.48774543]\n [ -3.45371439   3.9181989             
 -0.24082728]\n [ -6.96302448   4.21026366   1.44711994]\n [ -7.87969868        
 5.79846886  -0.78511261]\n [-10.78133286   5.81142048  -0.84648024]\n          
 [-11.8662359    3.29989536  -0.95244669]\n [-10.99622451   1.73974586          
 1.12451429]\n [ -8.10667312   1.54851603   1.26889499]\n [ -7.38634931         
 0.60949289  -0.42720246]\n [ -7.54689462   0.42887612   2.9072937 ]\n          
 [-11.71491741   2.57780409   2.8730566 ]\n [-11.82906179  -0.1375502           
 0.91985645]\n [-11.67246746   2.49741789  15.99809549]\n [-11.3961548          
 2.46764447  -2.61872854]\n [-11.49901762   6.72383079   0.86463132]\n          
 [-11.45488099   6.88021936  -2.4787178 ]\n [ -7.16053217   7.72283927          
 -0.62296626]\n [ -7.16237073   4.98753475  -2.54719616]\n [ -7.62135567        
 5.10576741   3.19428815]\n [ -5.60001214   3.63137382   6.33923736]\n [        
 -3.24131461   1.86173378  10.36613153]\n [ -1.95956493   1.42302951  12.5877665
 ]\n [ -3.51702612   1.41982647  14.7189604 ]\n [ -6.01246267   1.85051425      
 14.14276714]\n [ -6.44392484   2.27456732  10.93200331]\n [ -8.11015882        
 1.96701173  15.90223604]\n [ -7.93934761   1.67908609  18.16061487]\n          
 [-10.33234981   2.43874688  14.75154711]\n [ -2.88048355   1.12090045          
 16.62483981]\n [  0.04918854   1.14112873  12.6830604 ]\n [  1.36786679        
 0.34547434   8.7419365 ]] (type=value_error)"                                  
                                                                                
outputs have been saved to mol_.json            
```

**Software versions**

- Which operating system and version are you using? Linux
- How did you install BespokeFit? conda
- Are you using Apple Silicon? If so, are you running BespokeFit in Rosetta (`osx-64`) or natively (`osx-arm64`)? No
- What is the output of running `conda list`?

<details><summary>Output of <code>conda list</code></summary><pre>

Please place the output of `conda list` here

</pre></details>

**Comment by mattwthompson** [comment] 2023-10-24 15:12
A proton transferred from the N+ to an O-

**Comment by xiki-tempula** [comment] 2023-10-24 15:15
But if you look at the molecule. This looks like a normal molecule that shall be supported.

**Comment by j-wags** [comment] 2023-10-24 15:22
Is the the initial input structure, or the final structure at the end of the optimization?

**Comment by xiki-tempula** [comment] 2023-10-24 15:23
This is the initial structure, which gives the error. Then I have also tested using smiles string as input which would also give the same error.

**Comment by mattwthompson** [comment] 2023-10-24 15:27
Torsion drives involve many structures, not just the input geometry - it looks like (at least) one of them has the zwitterion wrap back around itself into a structure that enables a proton transfer from the positive nitrogen to negative oxygen. I'm working on reproducing your issue and highlighting the geometry that causes this error.

**Comment by j-wags** [comment] 2023-10-24 15:32
One major driver of this is that bespokefit does the torsiondrives+opts in vacuum, so these types of transfers can occur over moderate distances. Once a proton transfer occurs, the optimization is no good, because the energies no longer correspond to the molecule the user intended to fit. 

Users have suggested implementing an automated "throw out the bad data and finish the fit with the good points", but without good data on how many complete opts we need to do a good fit, we currently have it error out if even one point has the proton transfer (for more details, the PR for proton transfer error logic is https://github.com/openforcefield/openff-bespokefit/pull/193)

**Comment by mattwthompson** [comment] 2023-10-24 15:33
My quick thoughts are

* I wonder if this proton transfer occurs with Psi4 or only XTB
* I wonder how bad it would be to throw out a portion of structures in a torsion drive. Using less data/quietly filtering out some inputs nudges us down a dubious path, but I also don't think it's great UX for an entire fix to fail when a small number of points are garbage, assuming the fit could still proceed with decent results - ha, it looks like I'm not the first person to think of this

**Comment by j-wags** [comment] 2023-10-24 17:08
At least for PCM with Psi4 - I recall a few things preventing that from being production-ready:

* Slow performance
* Lack of parallelization
* Some sort of [ongoing deployment/compatibility issue](https://github.com/PCMSolver/pcmsolver/issues/206) for the last few months (I'm running into this in another area today)

**Comment by xiki-tempula** [comment] 2023-10-25 05:57
I do agree that implicit solvation model is not the ideal solution. In addition to the problem that you have described, I found that implicit solvent doesn't always prevent proton transfer.
I prefer putting on a HBond constrain after the initial minimisation.

**Comment by mattwthompson** [comment] 2023-10-25 19:18
It took a day, but I can reproduce the original issue

```shell
$ openff-bespoke executor run --smiles             "c1cc(cc(c1)NC2CC[NH2+]CC2)C3=C(C(=C(S3)C(=O)[O-])OCC(=O)[O-])Br"    \
                            --workflow           "default"              \
                            --output             "mol.json"   \
                            --output-force-field "mol.offxml" \
                            --n-qc-compute-workers 4                    \
                            --qc-compute-n-cores   1                    \
                            --default-qc-spec xtb gfn2xtb none

──────────────────────────────── OpenFF Bespoke ────────────────────────────────

[✓] bespoke executor launched

1. preparing the bespoke workflow

[✓] 1 molecules found
[✓] fitting schemas generated

2. submitting the workflow

[✓] the following workflows were submitted
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━┓
┃ ID ┃ SMILES                                                    ┃ NAME ┃ FILE ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━┩
│ 1  │ c1cc(cc(c1)NC2CC[NH2+]CC2)C3=C(C(=C(S3)C(=O)[O-])OCC(=O)[ │      │      │
│    │ O-])Br                                                    │      │      │
└────┴───────────────────────────────────────────────────────────┴──────┴──────┘

3. running the fitting pipeline

[✓] fragmentation successful
[✓] qc-generation successful
[x] optimization failed

 "Failed to inject the bespoke QC data into the optimization schema: 1
 validation error for TorsionProfileTargetSchema\nreference_data\n  Target
 record -30: Reference data does not match target.\nExpected mapped SMILES:
 [H:1]1((((1[H:8])[N:9]([H:10])[C:11]2([C:16]([C:15]([N+:14]([C:13]([C:12]2([H:2
 5])[H:26])([H:23])[H:24])([H:21])[H:22])([H:19])[H:20])([H:17])[H:18])[H:27])[H
 :28])[C:29]3=[C:30]([C:31](=[C:32]([S:33]3)[C:34](=[O:35])[O-:36])[H:37])[H:38]
 )[H:39]\nThe following connections were expected but not found: {(14, 21)}\nThe
 following connections were found but not expected: {(21, 36)}\nThe reference
 geometry is: [[  2.98276542   0.62550606   4.40553353]\n [  1.09784268
 1.28442185   4.82909229]\n [  0.19779977   1.13567506   7.27675924]\n [
 -2.2401608    1.98862808   7.82139354]\n [ -3.72739167   2.96508974
 5.88192073]\n [ -2.84372902   3.09513478   3.40507362]\n [ -0.38641273
 2.24533095   2.91290608]\n [  0.34272279   2.34893098   1.0071995 ]\n [
 -4.22253952   4.18599376   1.48722015]\n [ -3.45195991   3.91360181
 -0.24123289]\n [ -6.96102528   4.20973173   1.44636923]\n [ -7.8759671
 5.79801319  -0.7865196 ]\n [-10.77757205   5.81367375  -0.84824855]\n
 [-11.86483738   3.30313674  -0.95340028]\n [-10.99654051   1.74296938
 1.12426634]\n [ -8.10720052   1.54903185   1.26905555]\n [ -7.38755695
 0.60865809  -0.42658605]\n [ -7.54869108   0.42950003   2.90796464]\n
 [-11.71463266   2.58239195   2.87240138]\n [-11.83112503  -0.13361998
 0.92025078]\n [-11.67487704   2.50425924  15.99792153]\n [-11.3953206
 2.46980534  -2.61930202]\n [-11.49460189   6.72741486   0.86242755]\n
 [-11.44989121   6.8824975   -2.48097627]\n [ -7.15502807   7.72177018
 -0.62493926]\n [ -7.15917419   4.98580901  -2.54823829]\n [ -7.61864679
 5.10652123   3.19315122]\n [ -5.598968     3.63140637   6.33868919]\n [
 -3.24277195   1.86126373  10.36709634]\n [ -1.96158072   1.42329064
 12.58919228]\n [ -3.51963266   1.42214773  14.71996535]\n [ -6.01482927
 1.85363409  14.14335546]\n [ -6.44529366   2.27595743  10.93225067]\n [
 -8.11276827   1.97216475  15.90239066]\n [ -7.94164954   1.68537141  18.1608861
 ]\n [-10.33477337   2.44427546  14.75141654]\n [ -2.88356814   1.12407824
 16.62612678]\n [  0.04703065   1.14054875  12.68506739]\n [  1.36505922
 0.34005999   8.74329898]] (type=value_error)"

outputs have been saved to mol.json


worker: Warm shutdown (MainProcess)

worker: Warm shutdown (MainProcess)

worker: Warm shutdown (MainProcess)
```

I don't know the path forward here - I think BespokeFit is behaving well for what it's scoped to do. A better error message would be nice (#281) as would larger changes like implicit solvent or bond constraints might be nice, PRs for those might be considered. (I'm a little bit less sure about bond constraints with QC calculations as that's out of my wheelhouse - others are better equipped to say if such a change fits in here.)

**Comment by xiki-tempula** [comment] 2023-10-26 06:56
I think the easiest path would be for this particular torsion, one doesn't fit it? So other torsions are optimised but this torsion is just taken from the base ff (like sage).

**Comment by jthorton** [comment] 2023-10-26 10:57
Hi @xiki-tempula I think that skipping the problem torsion would be a good idea! I like the idea of adding an option which controls what should be done in this situation by default it will raise this error but then users can choose an option like skip or add h-constraint or anything else we add later. I think the important bit is that we still make it clear that this has happened and we will be skipping the torsion. Ill look into adding an option to skip these problem torsions as a start!

**Comment by xiki-tempula** [comment] 2023-10-26 10:58
@jthorton Thank you very much. Looks like a good plan.

**Comment by mattwthompson** [comment] 2023-10-31 17:02
Just to keep things tidy, I'm closing this in favor of a summarized feature request in #295.

**Closed by mattwthompson** 2023-10-31 17:02 UTC
